spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/MovieProject
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    view:
      prefix: /
      suffix: .html
  messages:
    basename: errors

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 3000


